 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  qvhQ: # name of the dataset builder
    data_type: videos # [images|videos|features]
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/annotations/QVHighlights/lavis/train_mcqa.json
          storage: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/annotations/QVHighlights/lavis/train_mcqa.json
        val:
          url: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/annotations/QVHighlights/lavis/val.json
          storage: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/annotations/QVHighlights/lavis/val.json
        test:
          # url: Your/path/to/test_dummy.json
          # storage: Your/path/to/test_dummy.json
          url: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/annotations/QVHighlights/lavis/val.json
          storage: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/annotations/QVHighlights/lavis/val.json
      videos:
        storage: /pfss/mlde/workspaces/mlde_wsp_Rohrbach/data/raw/QVHighlights
